version: 1
builder:
  configs:
    - documentation_targets: [XtreamcodeSwiftAPI]
      scheme: xtreamcode-swift-api
      swift_version: "5.10"
      platform: iOS
      xcode_version: "15.0"
    - documentation_targets: [XtreamcodeSwiftAPI]
      scheme: xtreamcode-swift-api
      swift_version: "6.0"
      platform: macOS
      xcode_version: "15.0"
    - documentation_targets: [XtreamcodeSwiftAPI]
      scheme: xtreamcode-swift-api
      swift_version: "5.10"
      platform: tvOS
      xcode_version: "15.0"
